on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: julien_kowalski.tex
      - name: Compile LaTeX document - EN
        uses: xu-cheng/latex-action@master
        with:
          root_file: julien_kowalski-EN.tex
      - run: mkdir -p out
      - run: mv julien_kowalski.pdf out/cv_julien_kowalski.pdf
      - run: mv julien_kowalski-EN.pdf out/cv_julien_kowalski-EN.pdf
      - name: Create release
        run: |
          set -x
          assets=()
          for asset in out/*.pdf; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}